services:
  - type: web
    name: excellent-prof-backend
    runtime: node
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build && npx prisma generate
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
      - key: PORT
        value: 4000
